[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_transfer_pda = "3bgJ8TjDebaWM9PRZXLFoviajmunXPGdbWwYBxVsGdme"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabeth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
